name: "Check PR"

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: "Check PR"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn

      - run: yarn install

      - run: yarn lint

      - run: yarn lint:format

      - run: yarn lint:types
